---
# Setups shared configs for Linux/Mac machines
# Prequisites:
# 1. dropbox
# 2. byobu
- hosts: localhost
  tasks:
  - name: linking
    file: src={{ item.src }} force=yes dest={{ item.dest }} state=link
    with_items:
      - { src: "{{ CONFIGS }}/vimrc", dest: "{{ ansible_env.HOME }}/.vimrc" }
      - { src: "{{ CONFIGS }}/profile", dest: "{{ ansible_env.HOME }}/.profile" }
      - { src: "{{ CONFIGS }}/bashrc", dest: "{{ ansible_env.HOME }}/.bashrc" }
      - { src: "{{ CONFIGS }}/gitconfig", dest: "{{ ansible_env.HOME }}/.gitconfig" }
      - { src: "{{ CONFIGS }}/gitignore", dest: "{{ ansible_env.HOME }}/.gitignore" }
      - { src: "{{ CONFIGS }}/tmux.conf", dest: "{{ ansible_env.HOME }}/.tmux.conf" }
      - { src: "{{ CONFIGS }}/bash_aliases", dest: "{{ ansible_env.HOME }}/.bash_aliases" }
#      - { src: "{{ CONFIGS }}/tmux.conf", dest: "{{ ansible_env.HOME }}/.byobu/.tmux.conf" }
      - { src: "{{ CONFIGS }}/vim", dest: "{{ ansible_env.HOME }}/.vim" }
      - { src: "{{ CONFIGS }}/dbvis", dest: "{{ ansible_env.HOME }}/.dbvis" }
      - { src: "{{ CONFIGS }}/ssh", dest: "{{ ansible_env.HOME }}/.ssh" }

  - name: find Idea
    command: find -L -f {{ ansible_env.HOME }}/Applications /Applications -name idea -print -quit
    register: idea_path
    ignore_errors: True
    changed_when: false

  - name: idea config path
    lineinfile: dest="{{ idea_path.stdout|replace("MacOS/idea", "bin/idea.properties") }}" line="idea.config.path={{ CONFIGS }}/idea13-config"
    when: idea_path|success
  
  - name: set idea vm max mem
    lineinfile: dest="{{ idea_path.stdout|replace("MacOS/idea", "bin/idea.vmoptions") }}" line="-Xmx2048m"
    when: idea_path|success
  
  - name: set idea jdk to 1.7
    lineinfile: dest="{{ idea_path.stdout|replace("MacOS/idea", "bin/idea.properties") }}" line="JVMVersion=1.7*"
    args:
        regexp: '^JVMVersion=\d\.\d\*$'
    when: idea_path|success
    
  vars:
    - CONFIGS: "{{ ansible_env.HOME }}/Dropbox/configs"
